default_currency: USD
currency_symbol: "$"
locale: en_US
date_format: "2006-01-02" 
timezone: "Local"

default_category: "uncategorized"
custom_categories:
  - food
  - transport
  - rent
  - entertainment
  - subscriptions
  - health
  - savings
  - income


color_output: true
show_totals_on_list: true

enable_budgeting: true
warn_if_budget_exceeded: true
budget_warning_threshold: 90

auto_backup: true
backup_location: "./backups"
backup_frequency: "weekly"  


